package Bank;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/** 
 * Bank Login UI
 * User ID and Password are restrict to 4 digits
 * @author Pablo
 */
public class AITBankLoginUI extends javax.swing.JFrame{

    /**
     * Creates new form AITBankLoginUI
     */
    public AITBankLoginUI() {
        initComponents();
        
    }
    /**
     * Method to check empty fields
     * @throws Exceptions.EmptyInputException
     */
    public void checkEmptyFields() throws Exceptions.EmptyInputException{
        if(jTextFieldUserID.getText().isEmpty() && jPasswordField.getText().isEmpty())
        {
            throw new Exceptions.EmptyInputException("Enter user information.");
        }
    }
    
    /**
     * Method to Check user information on DB
     * @throws Exceptions.EmptyInputException
     * @throws Exception
     * @return true if found user, false if not
     */
    private boolean databaseUserCheck() throws  Exception, SQLException{        
        try{
            String connectionURL = "jdbc:derby://localhost:1527/BankDatabase";
            Connection conn = DriverManager.getConnection(connectionURL, "bank","bank");
            
            String ID = jTextFieldUserID.getText();
            String PIN = jPasswordField.getText();
          
            String sql = "SELECT * FROM CUSTOMER WHERE ID = "+ID+" AND PIN = "+PIN;
            Helper.Constants.UserID = ID; //Get user ID for use in future
            
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            
            //SELECT ALL
            rs.next();
            int row = rs.getRow();
           
            
            if(row > 0)
            {
                rs.close();
                st.close();
                conn.close();
                return true;
            }
            else    
            {
                rs.close();
                st.close();
                conn.close();
                return false;
            }            
                            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOptions = new javax.swing.JPanel();
        jLabelOptions = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        jButtonNumber1 = new javax.swing.JButton();
        jButtonNumber2 = new javax.swing.JButton();
        jButtonNumber3 = new javax.swing.JButton();
        jButtonNumber4 = new javax.swing.JButton();
        jButtonNumber5 = new javax.swing.JButton();
        jButtonNumber6 = new javax.swing.JButton();
        jButtonNumber7 = new javax.swing.JButton();
        jButtonNumber8 = new javax.swing.JButton();
        jButtonNumber9 = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonEnter = new javax.swing.JButton();
        jButtonNumber0 = new javax.swing.JButton();
        jButtonNumber10 = new javax.swing.JButton();
        jButtonNumber11 = new javax.swing.JButton();
        jButtonNumber12 = new javax.swing.JButton();
        jPanelScreen = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelUserID = new javax.swing.JLabel();
        jTextFieldUserID = new javax.swing.JTextField();
        jLabelUserPIN = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelError = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelOptions.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabelOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Card_Money_1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelOptionsLayout = new javax.swing.GroupLayout(jPanelOptions);
        jPanelOptions.setLayout(jPanelOptionsLayout);
        jPanelOptionsLayout.setHorizontalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOptions)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOptionsLayout.setVerticalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOptionsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelOptions))
        );

        jPanelButtons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanelButtons.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonNumber1.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNumber1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNumber1.setForeground(new java.awt.Color(102, 102, 102));
        jButtonNumber1.setLabel("1");
        jButtonNumber1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNumber1MouseClicked(evt);
            }
        });

        jButtonNumber2.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNumber2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNumber2.setForeground(new java.awt.Color(102, 102, 102));
        jButtonNumber2.setText("2");
        jButtonNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber2ActionPerformed(evt);
            }
        });

        jButtonNumber3.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNumber3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNumber3.setForeground(new java.awt.Color(102, 102, 102));
        jButtonNumber3.setText("3");
        jButtonNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber3ActionPerformed(evt);
            }
        });

        jButtonNumber4.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNumber4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNumber4.setForeground(new java.awt.Color(102, 102, 102));
        jButtonNumber4.setLabel("4");
        jButtonNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber4ActionPerformed(evt);
            }
        });

        jButtonNumber5.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNumber5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNumber5.setForeground(new java.awt.Color(102, 102, 102));
        jButtonNumber5.setLabel("5");
        jButtonNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber5ActionPerformed(evt);
            }
        });

        jButtonNumber6.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNumber6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNumber6.setForeground(new java.awt.Color(102, 102, 102));
        jButtonNumber6.setLabel("6");
        jButtonNumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber6ActionPerformed(evt);
            }
        });

        jButtonNumber7.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNumber7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNumber7.setForeground(new java.awt.Color(102, 102, 102));
        jButtonNumber7.setLabel("7");
        jButtonNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber7ActionPerformed(evt);
            }
        });

        jButtonNumber8.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNumber8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNumber8.setForeground(new java.awt.Color(102, 102, 102));
        jButtonNumber8.setLabel("8");
        jButtonNumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber8ActionPerformed(evt);
            }
        });

        jButtonNumber9.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNumber9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNumber9.setForeground(new java.awt.Color(102, 102, 102));
        jButtonNumber9.setText("9");
        jButtonNumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber9ActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(255, 0, 0));
        jButtonCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(255, 255, 0));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClearMouseClicked(evt);
            }
        });

        jButtonEnter.setBackground(new java.awt.Color(0, 204, 0));
        jButtonEnter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEnter.setText("Enter");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jButtonNumber0.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNumber0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNumber0.setForeground(new java.awt.Color(102, 102, 102));
        jButtonNumber0.setText("0");
        jButtonNumber0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber0ActionPerformed(evt);
            }
        });

        jButtonNumber10.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNumber10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNumber10.setForeground(new java.awt.Color(102, 102, 102));

        jButtonNumber11.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNumber11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNumber11.setForeground(new java.awt.Color(102, 102, 102));

        jButtonNumber12.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNumber12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNumber12.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelButtonsLayout.createSequentialGroup()
                        .addComponent(jButtonNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelButtonsLayout.createSequentialGroup()
                        .addComponent(jButtonNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelButtonsLayout.createSequentialGroup()
                        .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumber10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                                .addComponent(jButtonNumber0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNumber11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonNumber12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                                .addComponent(jButtonNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNumber0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNumber10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonNumber11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelScreen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanelScreen.setPreferredSize(new java.awt.Dimension(560, 294));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Enter your user Information");

        jLabelUserID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUserID.setForeground(new java.awt.Color(102, 102, 102));
        jLabelUserID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserID.setText("Account ID");

        jTextFieldUserID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldUserID.setForeground(new java.awt.Color(0, 153, 153));
        jTextFieldUserID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldUserIDKeyTyped(evt);
            }
        });

        jLabelUserPIN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUserPIN.setForeground(new java.awt.Color(102, 102, 102));
        jLabelUserPIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserPIN.setText("PIN");

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_man_lock_password_security-512_2.png"))); // NOI18N

        jPasswordField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(0, 153, 153));
        jPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyTyped(evt);
            }
        });

        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setText("  ");
        jLabelError.setToolTipText("");

        javax.swing.GroupLayout jPanelScreenLayout = new javax.swing.GroupLayout(jPanelScreen);
        jPanelScreen.setLayout(jPanelScreenLayout);
        jPanelScreenLayout.setHorizontalGroup(
            jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelUserPIN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldUserID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUserID, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelIcon)
                .addGap(65, 65, 65))
            .addGroup(jPanelScreenLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelScreenLayout.setVerticalGroup(
            jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScreenLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelTitle)
                .addGroup(jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelScreenLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabelIcon))
                    .addGroup(jPanelScreenLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelUserID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUserPIN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabelLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
        //clean fields and set focus
        jLabelError.setText("  ");//clean error message
        jTextFieldUserID.setText("");
        jTextFieldUserID.requestFocusInWindow();
        jPasswordField.setText("");       
    }//GEN-LAST:event_jButtonCancelMouseClicked

    private void jButtonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClearMouseClicked
        jLabelError.setText("  ");//clean error message
        //clean field that has info and set focus
        if(jPasswordField.getText().length() > 0 && jTextFieldUserID.getText().length() > 0)
        {
            jPasswordField.setText("");
            jTextFieldUserID.setText("");
            jTextFieldUserID.requestFocusInWindow();
        }
        if(jTextFieldUserID.getText().length() > 0)
        {
            jTextFieldUserID.setText("");
            jTextFieldUserID.requestFocusInWindow();
        }
        if(jPasswordField.getText().length() > 0)
        {
            jPasswordField.setText("");
            jPasswordField.requestFocusInWindow();
        }
    }//GEN-LAST:event_jButtonClearMouseClicked

    private void jButtonNumber1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNumber1MouseClicked
        if(jTextFieldUserID.getText().length() < 4)
        {
            jTextFieldUserID.setText(jTextFieldUserID.getText()+"1");
        }
        else if(jPasswordField.getText().length() < 4)
        {
            jPasswordField.setText(jPasswordField.getText()+"1");
        }
    }//GEN-LAST:event_jButtonNumber1MouseClicked

    private void jButtonNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber2ActionPerformed
        if(jTextFieldUserID.getText().length() < 4)
        {
            jTextFieldUserID.setText(jTextFieldUserID.getText()+"2");
        }
        else if(jPasswordField.getText().length() < 4)
        {
            jPasswordField.setText(jPasswordField.getText()+"2");
        }
    }//GEN-LAST:event_jButtonNumber2ActionPerformed

    private void jButtonNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber3ActionPerformed
        if(jTextFieldUserID.getText().length() < 4)
        {
            jTextFieldUserID.setText(jTextFieldUserID.getText()+"3");
        }
        else if(jPasswordField.getText().length() < 4)
        {
            jPasswordField.setText(jPasswordField.getText()+"3");
        }
    }//GEN-LAST:event_jButtonNumber3ActionPerformed

    private void jButtonNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber4ActionPerformed
        if(jTextFieldUserID.getText().length() < 4)
        {
            jTextFieldUserID.setText(jTextFieldUserID.getText()+"4");
        }
        else if(jPasswordField.getText().length() < 4)
        {
            jPasswordField.setText(jPasswordField.getText()+"4");
        }
    }//GEN-LAST:event_jButtonNumber4ActionPerformed

    private void jButtonNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber5ActionPerformed
        if(jTextFieldUserID.getText().length() < 4)
        {
            jTextFieldUserID.setText(jTextFieldUserID.getText()+"5");
        }
        else if(jPasswordField.getText().length() < 4)
        {
            jPasswordField.setText(jPasswordField.getText()+"5");
        }
    }//GEN-LAST:event_jButtonNumber5ActionPerformed

    private void jButtonNumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber6ActionPerformed
        if(jTextFieldUserID.getText().length() < 4)
        {
            jTextFieldUserID.setText(jTextFieldUserID.getText()+"6");
        }
        else if(jPasswordField.getText().length() < 4)
        {
            jPasswordField.setText(jPasswordField.getText()+"6");
        }
    }//GEN-LAST:event_jButtonNumber6ActionPerformed

    private void jButtonNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber7ActionPerformed
        if(jTextFieldUserID.getText().length() < 4)
        {
            jTextFieldUserID.setText(jTextFieldUserID.getText()+"7");
        }
        else if(jPasswordField.getText().length() < 4)
        {
            jPasswordField.setText(jPasswordField.getText()+"7");
        }
    }//GEN-LAST:event_jButtonNumber7ActionPerformed

    private void jButtonNumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber8ActionPerformed
        if(jTextFieldUserID.getText().length() < 4)
        {
            jTextFieldUserID.setText(jTextFieldUserID.getText()+"8");
        }
        else if(jPasswordField.getText().length() < 4)
        {
            jPasswordField.setText(jPasswordField.getText()+"8");
        }
    }//GEN-LAST:event_jButtonNumber8ActionPerformed

    private void jButtonNumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber9ActionPerformed
        if(jTextFieldUserID.getText().length() < 4)
        {
            jTextFieldUserID.setText(jTextFieldUserID.getText()+"9");
        }
        else if(jPasswordField.getText().length() < 4)
        {
            jPasswordField.setText(jPasswordField.getText()+"9");
        }
    }//GEN-LAST:event_jButtonNumber9ActionPerformed

    private void jButtonNumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber0ActionPerformed
        if(jTextFieldUserID.getText().length() < 4)
        {
            jTextFieldUserID.setText(jTextFieldUserID.getText()+"0");
        }
        else if(jPasswordField.getText().length() < 4)
        {
            jPasswordField.setText(jPasswordField.getText()+"0");
        }
    }//GEN-LAST:event_jButtonNumber0ActionPerformed

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
       try{
           checkEmptyFields();
           boolean login = databaseUserCheck();
            
            if(login)
            {
                Helper.displayScreens display = new Helper.displayScreens();
                display.openMainUI(); //open Main Screen
                this.setVisible(false);//close current screen
            }
            else{
                jLabelError.setText(Helper.Constants.LoginError);
            }
       }
       catch(Exceptions.EmptyInputException ex){
           jLabelError.setText(ex.toString());
       }
       catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jButtonEnterActionPerformed

    private void jPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyTyped
        //Check for number only and maximum 4 character
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))||
            (vchar == KeyEvent.VK_BACK_SPACE)||
            (vchar == KeyEvent.VK_DELETE)||
            (jPasswordField.getText().length() >= 4))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jPasswordFieldKeyTyped

    private void jTextFieldUserIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUserIDKeyTyped
        //Check for number only and maximum 4 character
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar))||
            (vchar == KeyEvent.VK_BACK_SPACE)||
            (vchar == KeyEvent.VK_DELETE)||
            (jTextFieldUserID.getText().length() >= 4))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldUserIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AITBankLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AITBankLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AITBankLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AITBankLoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AITBankLoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JButton jButtonNumber0;
    private javax.swing.JButton jButtonNumber1;
    private javax.swing.JButton jButtonNumber10;
    private javax.swing.JButton jButtonNumber11;
    private javax.swing.JButton jButtonNumber12;
    private javax.swing.JButton jButtonNumber2;
    private javax.swing.JButton jButtonNumber3;
    private javax.swing.JButton jButtonNumber4;
    private javax.swing.JButton jButtonNumber5;
    private javax.swing.JButton jButtonNumber6;
    private javax.swing.JButton jButtonNumber7;
    private javax.swing.JButton jButtonNumber8;
    private javax.swing.JButton jButtonNumber9;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelOptions;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUserID;
    private javax.swing.JLabel jLabelUserPIN;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelOptions;
    private javax.swing.JPanel jPanelScreen;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUserID;
    // End of variables declaration//GEN-END:variables
}
